# Generated by Django 2.2 on 2019-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('email', models.CharField(default='NR', max_length=50)),
                ('phone', models.CharField(default='NR', max_length=20)),
                ('address', models.CharField(default='NR', max_length=40)),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='antusu_user'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(age__gte=0), name='positive_age'),
        ),
    ]
