# Generated by Django 2.2.4 on 2019-12-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoe', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_size', models.FloatField(default=0.0, null=True)),
                ('eu_size', models.FloatField(default=0.0, null=True)),
                ('status', models.CharField(blank=True, choices=[('R', 'Returned'), ('P', 'Purchased'), ('A', 'Available')], default='A', help_text='Shoe availability', max_length=1)),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Purchase')),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoe.Shoe')),
            ],
        ),
    ]
