# Generated by Django 2.2 on 2019-11-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='__', max_length=40, null=True)),
                ('release_date', models.DateTimeField(null=True, verbose_name='release date')),
                ('price', models.FloatField(default=0.0, null=True)),
                ('description', models.CharField(default='_', max_length=40, null=True)),
                ('type', models.CharField(default='_', max_length=40, null=True)),
                ('height', models.FloatField(default=0.0, null=True)),
                ('color', models.CharField(default='_', max_length=20, null=True)),
                ('image_route', models.CharField(default='blank.png', max_length=2000, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
        ),
    ]
